-- Hosted Codex App Server control-plane state for the Vite web application.
-- Supabase owns user identity, authorization, run persistence, and Realtime delivery.
-- ChatGPT tokens remain in the external Codex worker's per-user CODEX_HOME.

create table if not exists public.codex_connections (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null unique references public.recruiter_workspaces(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'disconnected'
    check (status in ('disconnected', 'connecting', 'connected', 'error')),
  account_email text,
  plan_type text,
  auth_mode text,
  runtime_id text,
  login_id text,
  last_error text,
  connected_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, workspace_id)
);

create table if not exists public.codex_runs (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.recruiter_workspaces(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  thread_id text,
  turn_id text,
  model text not null default 'gpt-5.6',
  prompt text not null,
  status text not null default 'queued'
    check (status in ('queued', 'running', 'completed', 'failed', 'cancelling', 'cancelled')),
  output text not null default '',
  error text,
  metadata jsonb not null default '{}'::jsonb,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.codex_run_events (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.codex_runs(id) on delete cascade,
  workspace_id uuid not null references public.recruiter_workspaces(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  sequence bigint not null,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (run_id, sequence)
);

create index if not exists codex_connections_user_id_idx
  on public.codex_connections (user_id);

create index if not exists codex_runs_workspace_created_idx
  on public.codex_runs (workspace_id, created_at desc);

create index if not exists codex_runs_user_status_idx
  on public.codex_runs (user_id, status, created_at desc);

create index if not exists codex_run_events_run_sequence_idx
  on public.codex_run_events (run_id, sequence);

drop trigger if exists set_codex_connections_updated_at on public.codex_connections;
create trigger set_codex_connections_updated_at
before update on public.codex_connections
for each row execute function public.set_updated_at();

drop trigger if exists set_codex_runs_updated_at on public.codex_runs;
create trigger set_codex_runs_updated_at
before update on public.codex_runs
for each row execute function public.set_updated_at();

alter table public.codex_connections enable row level security;
alter table public.codex_runs enable row level security;
alter table public.codex_run_events enable row level security;

drop policy if exists codex_connections_select_own on public.codex_connections;
create policy codex_connections_select_own
on public.codex_connections
for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists codex_runs_select_own on public.codex_runs;
create policy codex_runs_select_own
on public.codex_runs
for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists codex_run_events_select_own on public.codex_run_events;
create policy codex_run_events_select_own
on public.codex_run_events
for select
to authenticated
using ((select auth.uid()) = user_id);

revoke all on public.codex_connections from anon, authenticated;
revoke all on public.codex_runs from anon, authenticated;
revoke all on public.codex_run_events from anon, authenticated;
grant select on public.codex_connections to authenticated;
grant select on public.codex_runs to authenticated;
grant select on public.codex_run_events to authenticated;
grant all on public.codex_connections to service_role;
grant all on public.codex_runs to service_role;
grant all on public.codex_run_events to service_role;
grant usage, select on sequence public.codex_run_events_id_seq to service_role;

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'codex_connections'
    ) then
      alter publication supabase_realtime add table public.codex_connections;
    end if;

    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'codex_runs'
    ) then
      alter publication supabase_realtime add table public.codex_runs;
    end if;

    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'codex_run_events'
    ) then
      alter publication supabase_realtime add table public.codex_run_events;
    end if;
  end if;
end
$$;

comment on table public.codex_connections is
  'Supabase-visible connection state for a ChatGPT-authenticated Codex App Server runtime. No ChatGPT tokens are stored here.';

comment on table public.codex_runs is
  'Durable Codex runs requested by authenticated Jobraker Recruiter users.';

comment on table public.codex_run_events is
  'Ordered Codex App Server events used for Realtime progress and reconnect-safe replay.';
